### ISSUE TITLE
line smoothing or anti-aliasing ?

### ISSUE THREAD

**Issue by aero** [dk/PDL-Drawing-Prima#27]
lines and graphs drawn by this module are somewhat rough feel compared to R's ggplot2 or Python's matplotlib.
Can be improved ?

**Comment by run4flat** [comment]
Prima now supports anti-aliased line drawing. I was just playing around with it using the `lines` command and `pdl_lines` gets anti-aliasing! You have to turn anti-aliasing on explicitly with the method, i.e. `$widget->antialias(1)`. This does not seem to work right "out of the box" for PDL::Graphics::Prima unfortunately. More investigations will follow...

**Comment by dk** [comment]
$widget->antialias(1) works now after upgrading to use latest Prima API. Whether there should be needed a pdl property "antialiases" or the like (in line with lineWidth**s** etc), no idea. But that should anyway be another PR
