### ISSUE TITLE
Not compile with Prima-1.67

### ISSUE THREAD

**Issue by YuryPakhomov** [dk/PDL-Drawing-Prima#39]
Many errors like lib/PDL/Drawing/Prima.pm.PL:1294:20: error: «struct _Drawable_vmt» no contain element with name «set_translate».
 This because due to changes in  ./blib/lib/Prima/CORE/generic/Drawable.h of Prima-1.67. Now set_translate() is disappeared.

**Comment by run4flat** [comment]
Bah, I really need to hand this off to Dmitry. :-/
I'll try to get that next week.

**Comment by dk** [comment]
should be fixed now
